//
// Created by p0w3r on 16.03.16.
//

#ifndef PIPELINETESTC_11_PIPELINECONTROLLER_H
#define PIPELINETESTC_11_PIPELINECONTROLLER_H


class PipelineController {

};


#endif //PIPELINETESTC_11_PIPELINECONTROLLER_H
